name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.9.1'
    - run: yarn install
    - run: yarn build
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
