name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.9.1'
    - run: yarn install
    - name: Create environment file .env
      shell: bash
      run: cp sample.env .env
    - name: Create database
      run: yarn seed
    - run: yarn build
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./vendor-zip/vendor.zip ./dist package.json .env .sequelize.rc data
    - uses: actions/upload-artifact@master
      with:
        name: vendor
        path: vendor-zip  
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
